---

- ssh-key:
    name: default
    public: "~/.ssh/test.pub"
    private: "~/.ssh/test"

- rally-ci:
    pub-dir: /store/rally-ci/logs

- service:
    name: gerrit
    silent: true
    vote: false
    fake-stream: resources/gerrit-sample-stream.json
    module: rci.services.gerrit
    cfg-url-template: https://review.openstack.org/gitweb?p={project}.git;a=blob_plain;f=.rally-ci.yaml;hb={commit}
    cr-url-template: https://review.openstack.org/#q,{commit},n,z
    commit-url-template: http://git.openstack.org/cgit/{project}/commit/?id={commit}
    env:
      GERRIT_PROJECT: change.project
      GERRIT_REF: patchSet.ref
      GERRIT_REFUPD_NEW: refUpdate.newRev
      GERRIT_REFUPD_OLD: refUpdate.oldRev
      GERRIT_REFUPD_NAME: refUpdate.refName
      GERRIT_REFUPD_PROJECT: refUpdate.project
    ssh:
      hostname: review.openstack.org
      username: CHANGEME
      keys: ["~/.ssh/test"]

- service:
    name: status
    module: rci.services.status
    listen: ["0.0.0.0", "8080"]

- provider:
    name: my_lxc
    module: rci.provider.lxc
    hosts:
      - hostname: lxc-worker-1
        username: root
    vms:
      - 

- script:
    name: init_ubuntu_dev
    data: |
      apt-get -y update && apt-get -y upgrade && apt-get -y install git
      apt-get -y remove cloud-init
      mkdir /etc/skel/.ssh
      cp /root/.ssh/authorized_keys /etc/skel/.ssh/
      useradd -m rally
      echo 'rally ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/rally-42

- script:
    name: clone_projects
    user: rally
    data: |
      mkdir openstack-dev
      cd openstack-dev
      git clone git://git.openstack.org/openstack-dev/ci-sandbox.git

- script:
    name: git_checkout
    user: rally
    data: |
      cd $GERRIT_PROJECT && git checkout master && git pull
      git fetch https://review.openstack.org/$GERRIT_PROJECT $GERRIT_REF
      git checkout FETCH_HEAD && git rebase master || true
      git clean -fxd -e .tox -e *.egg-info
      git diff --name-only master

- script:
    name: tox
    user: rally
    data: |
      env && ls
      cd $GERRIT_PROJECT
      git status
      echo "tox -e${TOX_ENV}"

- job:
    name: tox
    provider: my_lxc
    vms:
      - name: ubuntu-1404-dev
        scripts:
          - git_checkout
          - tox

- job:
    parent: tox
    name: tox-pep8
    env:
      TOX_ENV: pep8

- job:
    parent: tox
    name: tox-py27
    env:
      TOX_ENV: py27

- job:
    parent: tox
    name: tox-py34
    env:
      TOX_ENV: py34

- matrix:
    name: tox-jobs
    projects:
      - openstack-dev/ci-sandbox
      - openstack/designate
      - openstack/murano
      - openstack/rally
      - openstack/nova
      - openstack/glance
      - openstack/neutron
    jobs:
      - tox-pep8
      - tox-py27
      - tox-py34
